name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - master
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Build ${{ matrix.arch }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x86_64
          - os: ubuntu-22.04
            arch: i686
          - os: ubuntu-22.04
            arch: aarch64
          - os: ubuntu-22.04
            arch: ppc64le
          - os: ubuntu-22.04
            arch: s390x
          - os: ubuntu-22.04
            arch: armv7l
          - os: windows-2019
            arch: AMD64
          - os: windows-2022
            arch: ARM64
          - os: windows-2019
            arch: x86
          - os: macos-13
            arch: universal2

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
        if: runner.os == 'Linux'

      - uses: yezz123/setup-uv@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_ARCHS: ${{ matrix.arch }}

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: wheelhouse/*.whl

      - name: Test wheel on host Linux
        if: runner.os == 'Linux' && matrix.arch == 'x86_64'
        run: |
          pip install wheelhouse/*manylinux*x86_64*.whl
          cppcheck --version
          python -m cppcheck --version
          python --version

  check_dist:
    name: Check dist
    needs: [build_wheels, build_sdist, test_sdist]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - run: pipx run twine check --strict dist/*

  upload_all:
    needs: [build_wheels, make_sdist]
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-22.04
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN  }}
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-22.04
    if: ${{ github.ref_name == github.event.repository.default_branch || (github.event_name == 'release' && github.event.action == 'published') }}
    permissions:
      contents: write
      id-token: write
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: |
            ~/vcpkg
            ~/.cache/pip
            ~/.cache/vcpkg
          key: cd-pages-${{ hashFiles('vcpkg.json') }}
          restore-keys: cd-pages-${{ hashFiles('vcpkg.json') }}

      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
        with:
          python-version: 3.x

      - name: Build Docs
        run: pipx run nox -s docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
